compute auto_scaling ready

diff --git a/config/functions b/config/functions
--- a/config/functions
+++ b/config/functions
@@ -12,27 +12,23 @@ function show_usage {
   echo
   echo "Available commands: (Note: work in progress)"
   echo "help: show this message"
-  echo "	Defaults 1: Ceph and compute nedes have the same HW configuration."
+  echo "	Defaults 1: Ceph and compute nodes have to have the same HW configuration."
   echo "	Defaults 2: Nodes Prebootstrapped and turned off, waiting for WOL packet."
   echo "	Defaults 3: Nodes are renamed, and have no spaces in names. This is URGENT!!!"
   echo "	Defaults 4: to be added..."
   echo "Steps:"
-  echo "	Step 1: Collect infromation about the nodes to add(from the file)"
-  echo "	Step 2: Create array  for storage and compute nodes."
-  echo "	Step 3: Send magick packet (WOL) for actual node."
-  echo "	Step 4: Monitor that the node is online and ready to deploy."
-  echo "	Step 5: Add nodes to cluster ID."
-  echo "	Step 6: Configure the node. Patch the YAML.(mac, ip)"
-  echo "	Step 7: Upload configuration back to FUEL."
-  echo "	Step 8: Deploy compute/ceph node."
+  echo "	Step 1: Add info to file config/nodes_to_add"
+  echo "	Step 2: Boot up the node, with sendind magic packet(wol)."
+  echo "	Step 3: Check tha node is online"
+  echo "	Step 4: Set hostname from file"
+  echo "	Step 5: Receive id of node my the MAC".
+  echo "	Step 6: Add nodes to cluster ID."
+  echo "	Step 7: Configure node network parameters."
+  echo "	Step 8: Configure node disks parameters."
+  echo "	Step 9: Deploy compute/ceph node."
   echo "Commands:"
-  echo "	boot compute: bootstrap one compute node"
-  echo "	boot storage: bootstrap one storage node"
-  echo "	stop compute: bootstrap one compute node"
-  echo "	stop storage: bootstrap one storage node"
-  echo "	deploy compute: deploy one compute node"
-  echo "	deploy storage: deploy one storage node"
-  echo "	remove node: remove node-id from fuel database, U still need to remove tails from cobbler;"
+  echo "	Comming soon..."
+
 
 }
 
@@ -57,7 +53,9 @@ function parse_options {
                     nonopts+=("$@")
                     return
                     ;;
-      -*)           echo "Unrecognized option: $opt" 1>&2
+      -*)           ${YELLOW}
+                    echo "Unrecognized option: $opt" 1>&2
+                    ${RESET}
                     exit 1
                     ;;
       *)            nonopts+=("$opt")
@@ -74,8 +72,8 @@ function list_nodes {
     do
       for((i=0;i<2;i++))
       do
-          echo ${columnname[$i]} $'\x1d' "${data[ (( $i + $offset )) ]}"
-      done | column -t -s$'\x1d'
+          echo ${columnname[$i]} $'\xr' ${data[ (( $i + $offset )) ]}
+      done | column -t -s$'\xr'
       (( offset += 2 ))
     done
 }
@@ -83,37 +81,36 @@ function list_nodes {
 function node_data {
 
   re='^[1-9]+$'
-    if [[ "$1" == '' ]]; then
-      ${GREEN}
-      echo "usage: $0 node 1 2 4" >&2; 
+  if [[ "$1" == '' ]]; then
+    ${GREEN}
+    echo "usage: $0 info 1 2 4" >&2; 
+    ${RESET}
+    exit 0
+  fi
+  for nodes in $@; do
+    if ! [[ $nodes =~ $re ]] ; then
+      ${RED}
+      echo "error: Not a number, should be in range [1..$nodes_count]" >&2;
       ${RESET}
-      exit 0
-    fi
-    for nodes in $@; do
-      if ! [[ $nodes =~ $re ]] ; then
-        ${RED}
-        echo "error: Not a number, should be in range [1..$nodes_count]" >&2;
-        ${RESET}
-        exit 1
-      elif
-          [[ $nodes > $nodes_count ]] ; then 
-          ${RED}
-          echo "ID of node out of range [1.."$nodes_count"] please check the file node_to_add"
-          ${RESET}
-      else
-         columnname=("MAC" "NAME")
-         for((i=0;i<2;i++))
-          do
-          echo ${columnname[$i]} $'\x1d' "${data[ (( (( $nodes - 1 )) * 2 + $i )) ]}"
-          done | column -t -s$'\x1d'
+      exit 1
+    elif
+      [[ $nodes > $nodes_count ]] ; then 
+      ${RED}
+      echo "ID of node number out of range [1.."$nodes_count"] please check the file node_to_add"
+      ${RESET}
+    else
+      columnname=("MAC" "NAME")
+      for((i=0;i<2;i++)) 
+       do
+         echo ${columnname[$i]} $'\xr' "${data[ (( (( $nodes - 1 )) * 2 + $i )) ]}"
+       done | column -t -s$'\xr'
       fi
     done
-#  node_count
+  node_count
 }
 
+function wol_and_check {
 
-
-function get_node_id {
   re='^[1-9]+$'
     if [[ "$1" == '' ]]; then
       ${GREEN}
@@ -121,52 +118,82 @@ function get_node_id {
       ${RESET}
       exit 0
     fi
-      if ! [[ $1 =~ $re ]] ; then
-        ${RED}
-        echo "error: Not a number, should be in range [1..$nodes_count]" >&2;
-        ${RESET}
-        exit 1
-      else
-        (( macid = (( (( $1 - 1 )) * 2 )) ))
-        echo ${data[ $macid ]}
-        #return ${data[ $macid ]}
+    if ! [[ $1 =~ $re ]] ; then
+      ${RED}
+      echo "error: Not a number, should be in range [1..$nodes_count]" >&2;
+      ${RESET}
+      exit 1
+    else
+      (( macid = (( (( $1 - 1 )) * 2 )) ))
+      echo ${data[ $macid ]}
+      wol_node ${data[ $macid ]}
+      check_ready node ${data[ $macid ]}
+      get_fuel_id ${data[ $macid ]}
+      set_hostname $1 $node_fuel_id
+      add_to_env $node_fuel_id
+      net_config ${data[ $macid ]}
+      set_ext_ip
+      deploy_changes
+      remove_from_list
      fi
-  check_ready online ${data[ $macid ]}
 
+}
+
+function remove_from_list {
+  exit 0
+}
+
+function add_to_env {
+    $FUEL --env $env_id node set --node-id $1 --role $role
+}
+
+function deploy_changes {
+    $FUEL --env $env_id deploy-changes
 }
 
 
 
+function get_fuel_id {
+    node_fuel_id=`$FUEL node | $GREP $1 | $AWK '{print $1}'`
+    return
+}
 
+function net_config {
+    config/manage_eth_by_roles --assign name --admin-pass $FUEL_ACCESS_password --admin-tenant admin --admin-username $FUEL_ACCESS_user --fuel $ADMIN_NETWORK_ipaddress --node $node_fuel_id --mgmt $mgmtif --public $publicif --storage $storageif --private $privateif --mgmtbondmode $mgmtbondmode --publicbondmode $publicbondmode --storagebondmode $storagebondmode --privatebondmode $privatebondmode
+}
 
-function boot {
-  update_credentials
-  offset=1
-  re='^[0-9]+$'
+function set_ext_ip {
+#not implemented yet
+#returns the net_id
+#NET_ID=$(sudo -u postgres psql -d nailgun -t -c "select id from network_groups where name = 'public' and group_id = 2")
+#inserts the public ip
+#sudo -u postgres psql -d nailgun -t -c "insert into ip_addrs (network,node,ip_addr) values ($NET_ID,8,'172.16.49.200');"
+
+#to check
+#sudo -u postgres psql -d nailgun -t -c "insert into ip_addrs (network,node,ip_addr) values ((select id from network_groups where name = 'public' and group_id = 2),8,'172.16.49.200');"
+exit 0
+}
+
+function set_hostname {
+
+  (( hostname_id = (( (( $1 - 1 )) * 2 + 1 )) ))
+  host_name=${data[ $hostname_id ]}
+  #debug echo $host_name
+
     if [[ "$1" == '' ]]; then
       ${GREEN}
-      echo "usage: $0 boot 0 1 2 4 or $0 boot first - to boot first spare node" >&2; 
+      echo "usage: $0 node 1 2 4" >&2; 
       ${RESET}
       exit 0
     fi
+        echo "Setting hostname for node-$2 to:" $host_name
+        fuel node --node-id $2 --setname $host_name
+}
 
-    for nodes in $@; do
-      if ! [[ $nodes =~ $re ]] ; then
-        ${RED}
-        echo "error: Not a number, should be in range [0..]" >&2;
-        ${RESET}
-        exit 1
-     else
-        let "offset= $nodes * 5"
-        node_mac=${data[@]:$offset + 3:1}
-        node_ip=${data[@]:$offset + 2:1}
-        echo "Sending wol packet to node with mac:" $node_mac
-        ether-wake -i ${ADMIN_NETWORK_interface} $node_mac
-        check_ready node $node_ip
-     fi
-    done
-#node_count
-
+function wol_node {
+  update_credentials
+  echo "Sending wol packet to node with mac:" $1
+  ether-wake -i ${ADMIN_NETWORK_interface} $1
 }
 
 function node_count {
@@ -175,15 +202,13 @@ function node_count {
   ${RESET}
 }
 
-
 function check_ready {
   #Uses a custom command to ensure a container is ready
   update_credentials
   failure=0
   echo "checking that node or service is available: $1 $2"
   case $1 in
-      node) retry_checker "ping -c 1 $2 | grep ttl" ;;
-      online) retry_checker "fuel node | grep '$2' | grep 'True'" ;;
+      node) retry_checker "fuel node | grep '$2' | grep 'True'" ;;
       *) echo "No defined test for determining if $1 is ready.";;
   esac
 
@@ -196,21 +221,12 @@ function check_ready {
   fi
 }
 
-
-
-
-
-
-
-
-
 function update_credentials {
   credentialfile=$(mktemp /tmp/servicepws.XXXXX)
   $GSC $ASTUTE_YAML > $credentialfile
   . $credentialfile
   rm -f $credentialfile
 }
-
 
 function retry_checker {
   tries=0
