quotest typo

diff --git a/config/functions b/config/functions
--- a/config/functions
+++ b/config/functions
@@ -62,6 +62,37 @@ function parse_options {
     done
 }
 
+function wol_and_check {
+
+    re='^[1-9]+$'
+    if [[ "$1" == '' ]]; then
+      ${GREEN}
+      echo "usage: $0 node 1 2 4" >&2; 
+      ${RESET}
+      exit 0
+    fi
+    if ! [[ $1 =~ $re ]] ; then
+      ${RED}
+      echo "error: Not a number, should be in range [1..$nodes_count]" >&2;
+      ${RESET}
+      exit 1
+    else
+      check_rc_fuel_node            ## Check that command fuel node working well
+      (( macid = (( (( $1 - 1 )) * 3 )) ))
+      check_active_deployments      ## Check that we have no nodes with status Deploying|provisioning and so on
+      wol_node ${data[ $macid ]}    ## Sending magick packet
+      check_ready node ${data[ $macid ]} ## Checking, that node Online
+      get_fuel_id ${data[ $macid ]} ## Getting the ID that fuel gave to the node
+#      set_ext_ip $1
+      set_hostname $1 $node_fuel_id ## Setting hostname
+      add_to_env $node_fuel_id
+      net_config $node_fuel_id
+#      disk_config $node_fuel_id     ## Comment this line if Compute
+      remove_from_list ${data[ $macid ]}
+      deploy_changes
+     fi
+
+}
 
 function list_nodes {
     columnname=("ADMIN MAC" "NAME" "IP")
@@ -107,37 +138,6 @@ function node_data {
   node_count
 }
 
-function wol_and_check {
-
-    re='^[1-9]+$'
-    if [[ "$1" == '' ]]; then
-      ${GREEN}
-      echo "usage: $0 node 1 2 4" >&2; 
-      ${RESET}
-      exit 0
-    fi
-    if ! [[ $1 =~ $re ]] ; then
-      ${RED}
-      echo "error: Not a number, should be in range [1..$nodes_count]" >&2;
-      ${RESET}
-      exit 1
-    else
-      check_rc_fuel_node            ## Check that command fuel node working well
-      (( macid = (( (( $1 - 1 )) * 3 )) ))
-      check_active_deployments      ## Check that we have no nodes with status Deploying|provisioning and so on
-      wol_node ${data[ $macid ]}    ## Sending magick packet
-      check_ready node ${data[ $macid ]} ## Checking, that node Online
-      get_fuel_id ${data[ $macid ]} ## Getting the ID that fuel gave to the node
-#      set_ext_ip $1
-      set_hostname $1 $node_fuel_id ## Setting hostname
-      add_to_env $node_fuel_id
-      net_config $node_fuel_id
-      disk_config $node_fuel_id     ## Comment this line if Compute
-      remove_from_list ${data[ $macid ]}
-      deploy_changes
-     fi
-
-}
 
 function check_active_deployments {
     n=`$FUEL nodes | egrep "deplo|disco|ready|provi" | egrep -v "ready|disco" | wc -l` ## Collecting the number of non-ready objects
@@ -198,7 +198,8 @@ function get_disks {
 
 
 function remove_from_list {
-    sed -e 's/^$1/#$1/' -i $NTA
+
+    sed -e 's/^'$1'/#'$1'/' -i $NTA
 }
 
 function add_to_env {
